In [101]:
pip install folium

Requirement already satisfied: folium in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (0.17.0)
Requirement already satisfied: branca>=0.6.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from folium) (0.7.2)
Requirement already satisfied: jinja2>=2.9 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from folium) (2.1.1)
Requirement already satisfied: requests in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from folium) (2024.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from jinja2>=2.9->folium) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from requests->folium) (2024.8.30)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 24.2
[notice] To update, run: C:\Users\Dell\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [102]:
import folium
#m=folium.Map(location=[28.644800, 77.216721])
m=folium.Map(location=[18.5204, 73.8567])

m

In [103]:
from branca.element import Figure
fig=Figure(width=550,height=350)

In [104]:
fig2=Figure(width=550,height=350)
m2=folium.Map(location=[28.644800, 77.216721])
fig2.add_child(m2)
folium.TileLayer('Stamen Terrain').add_to(m2)
folium.TileLayer('Stamen Toner').add_to(m2)
folium.TileLayer('Stamen Water Color').add_to(m2)
folium.TileLayer('cartodbpositron').add_to(m2)
folium.TileLayer('cartodbdark_matter').add_to(m2)
folium.LayerControl().add_to(m2)
m2

ValueError: Custom tiles must have an attribution.

In [ ]:
# Creating Basemap
fig3=Figure(width=550,height=350)
m3=folium.Map(location=[28.644800, 77.216721],tiles='cartodbpositron',zoom_start=11)
fig3.add_child(m3)

#Adding markers to the map
folium.Marker(location=[28.695800, 77.244721],popup='Default popup Marker1',tooltip='Click here to see Popup').add_to(m3)
folium.Marker(location=[28.645800, 77.214721],popup='<strong>Marker3</strong>',tooltip='<strong>Click here to see Popup</strong>').add_to(m3)
folium.Marker(location=[28.655800, 77.274721],popup='<h3 style="color:green;">Marker2</h3>',tooltip='<strong>Click here to see Popup</strong>').add_to(m3)

m3

In [ ]:
import folium as fl
from streamlit_folium import st_folium
import streamlit as st

def get_pos(lat,lng):
    return lat,lng

m = fl.Map()

m.add_child(fl.LatLngPopup())

map = st_folium(m, height=350, width=700)


data = get_pos(map['last_clicked']['lat'],map['last_clicked']['lng'])

if data is not None:
    st.write(data)

In [ ]:
from folium.plugins import MousePosition

In [ ]:
import folium
from folium.plugins import MousePosition
formatter = "function(num) {return L.Util.formatNum(num, 3) + ' º ';};"
#m=folium.Map(location=[28.644800, 77.216721])
m=folium.Map(location=[18.5204, 73.8567])
MousePosition(
    position="topright",
    separator=" | ",
    empty_string="NaN",
    lng_first=True,
    num_digits=20,
    prefix="Coordinates:",
    lat_formatter=formatter,
    lng_formatter=formatter,
).add_to(m)
m.add_child(folium.LatLngPopup())
coord=[[18.5204, 73.8567],
[18.5, 73.9],
[18.4, 74.8],[18.42, 74.6]]

folium.Circle(location=[18.5204, 73.8567], popup='Point 1A', fill_color='#000', radius=20000, weight=2, color="#000").add_to(m)
for i in coord:
   folium.Marker(i,
              icon=folium.Icon(color='blue',
                               prefix='fa',icon='111')).add_to(m)

folium.LatLngPopup()


m

In [ ]:
from streamlit_folium import st_folium

In [ ]:
lst=[]

In [ ]:
lst.append([1,5])

In [ ]:
lst

In [107]:
lst[0]

[1, 5]

In [116]:
import pandas as pd
coord=pd.read_csv('coordinate data.csv')

In [117]:
coord_clean=coord.drop(columns=['ID', 'LATLONLIST', 'CREATED_AT'])

In [118]:
coord.columns

Index(['ID', 'LATITUDE', 'LONGITUDE', 'LATLONLIST', 'CREATED_AT'], dtype='object')

In [119]:
coord_clean=coord_clean.sort_values(by=[ 'LATITUDE'])

     LATITUDE  LONGITUDE
0   17.824506  73.575439
7   18.008774  73.557587
9   18.203262  73.458710
8   18.203262  73.458710
10  18.234569  73.634491
14  18.285430  73.984680
5   18.393619  73.854218
11  18.419685  73.773193
4   18.457457  73.813019
13  18.484819  73.986053
2   18.487415  73.906403
1   18.506951  73.751221
3   18.536901  73.909149
12  18.555197  73.844572
6   18.591578  73.821259
15  18.672267  74.113769

In [120]:
coord_clean['LATITUDE_diff'] = abs(coord_clean['LATITUDE'].diff())

In [122]:
coord_clean
coord_clean['LATITUDE_diff'] = coord_clean['LATITUDE_diff'].fillna(0)
coord_clean

     LATITUDE  LONGITUDE  LATITUDE_diff
0   17.824506  73.575439       0.000000
1   18.506951  73.751221       0.682444
2   18.487415  73.906403       0.019535
3   18.536901  73.909149       0.049485
4   18.457457  73.813019       0.079444
5   18.393619  73.854218       0.063837
6   18.591578  73.821259       0.197959
7   18.008774  73.557587       0.582804
8   18.203262  73.458710       0.194488
9   18.203262  73.458710       0.000000
10  18.234569  73.634491       0.031307
11  18.419685  73.773193       0.185116
12  18.555197  73.844572       0.135513
13  18.484819  73.986053       0.070378
14  18.285430  73.984680       0.199389
15  18.672267  74.113769       0.386837

In [123]:
coord_clean['Group']=0
for index, row in coord_clean.iterrows():
    print(row['LATITUDE_diff'])

0.0
0.6824443736861383
0.019535442604627917
0.049485457432560054
0.07944412794881828
0.06383746910343646
0.1979593801320263
0.5828044478213457
0.19448806841524657
0.0
0.0313067113052341
0.18511580137321104
0.1355126297043192
0.07037830601290906
0.199388761174923
0.3868371607363663

In [125]:
count=0
for index, row in coord_clean.iterrows():
    if row['LATITUDE_diff']>0.2:
       count=count+1
       row['Group']=count
    else:
       row['Group']=count

In [126]:
len(coord_clean)

16

In [ ]:
coord_clean.iloc[1]['LATITUDE_dif']

In [130]:
count=0
rw=len(coord_clean)
for x in range(rw):
    print(coord_clean.iloc[x]['LATITUDE_diff'])
    if coord_clean['LATITUDE_diff'][x]>0.2:
           count=count+1
           coord_clean['Group'][x]=count
    else:
           coord_clean['Group'][x]=count

0.0
0.6824443736861383
0.019535442604627917
0.049485457432560054
0.07944412794881828
0.06383746910343646
0.1979593801320263
0.5828044478213457
0.19448806841524657
0.0
0.0313067113052341
0.18511580137321104
0.1355126297043192
0.07037830601290906
0.199388761174923
0.3868371607363663

C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\2931014464.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group'][x]=count

In [131]:
coord_clean

     LATITUDE  LONGITUDE  LATITUDE_diff  Group
0   17.824506  73.575439       0.000000      0
1   18.506951  73.751221       0.682444      1
2   18.487415  73.906403       0.019535      1
3   18.536901  73.909149       0.049485      1
4   18.457457  73.813019       0.079444      1
5   18.393619  73.854218       0.063837      1
6   18.591578  73.821259       0.197959      1
7   18.008774  73.557587       0.582804      2
8   18.203262  73.458710       0.194488      2
9   18.203262  73.458710       0.000000      2
10  18.234569  73.634491       0.031307      2
11  18.419685  73.773193       0.185116      2
12  18.555197  73.844572       0.135513      2
13  18.484819  73.986053       0.070378      2
14  18.285430  73.984680       0.199389      2
15  18.672267  74.113769       0.386837      3

In [132]:
cord_sorted=coord_clean.sort_values(['Group','LONGITUDE'],ascending=False).groupby('Group')

In [133]:
cord_sorted

In [134]:
coord_clean.groupby(['Group']).apply(lambda x: x.sort_values(["LONGITUDE"], ascending = False)).reset_index(drop=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\243065980.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  coord_clean.groupby(['Group']).apply(lambda x: x.sort_values(["LONGITUDE"], ascending = False)).reset_index(drop=True)

     LATITUDE  LONGITUDE  LATITUDE_diff  Group
0   17.824506  73.575439       0.000000      0
1   18.536901  73.909149       0.049485      1
2   18.487415  73.906403       0.019535      1
3   18.393619  73.854218       0.063837      1
4   18.591578  73.821259       0.197959      1
5   18.457457  73.813019       0.079444      1
6   18.506951  73.751221       0.682444      1
7   18.484819  73.986053       0.070378      2
8   18.285430  73.984680       0.199389      2
9   18.555197  73.844572       0.135513      2
10  18.419685  73.773193       0.185116      2
11  18.234569  73.634491       0.031307      2
12  18.008774  73.557587       0.582804      2
13  18.203262  73.458710       0.000000      2
14  18.203262  73.458710       0.194488      2
15  18.672267  74.113769       0.386837      3

In [135]:
coord_clean['LONGITUDE_diff'] = coord_clean.groupby(['Group'])['LONGITUDE'].diff().abs()

In [136]:
coord_clean

     LATITUDE  LONGITUDE  LATITUDE_diff  Group  LONGITUDE_diff
0   17.824506  73.575439       0.000000      0             NaN
1   18.506951  73.751221       0.682444      1             NaN
2   18.487415  73.906403       0.019535      1        0.155182
3   18.536901  73.909149       0.049485      1        0.002747
4   18.457457  73.813019       0.079444      1        0.096130
5   18.393619  73.854218       0.063837      1        0.041199
6   18.591578  73.821259       0.197959      1        0.032959
7   18.008774  73.557587       0.582804      2             NaN
8   18.203262  73.458710       0.194488      2        0.098877
9   18.203262  73.458710       0.000000      2        0.000000
10  18.234569  73.634491       0.031307      2        0.175781
11  18.419685  73.773193       0.185116      2        0.138702
12  18.555197  73.844572       0.135513      2        0.071379
13  18.484819  73.986053       0.070378      2        0.141481
14  18.285430  73.984680       0.199389      2        0.001373
15  18.672267  74.113769       0.386837      3             NaN

In [137]:
coord_clean['LONGITUDE_diff'] = coord_clean['LONGITUDE_diff'].fillna(0)

In [138]:
coord_clean['Group1']=0
count=0
rw=len(coord_clean)
for x in range(rw):
    print(coord_clean.iloc[x]['LONGITUDE_diff'])
    if coord_clean['LONGITUDE_diff'][x]>0.1:
           count=count+1
           coord_clean['Group1'][x]=count
    else:
           coord_clean['Group1'][x]=count

0.0
0.0
0.15518187424166285
0.002746581845002538
0.09613036457450619
0.041198748629525994
0.032959003094589434
0.0
0.09887694641949452
0.0
0.175781238079054
0.1387023831717613
0.07137898234798001
0.14148113246862692
0.0013732909318093789
0.0

C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  coord_clean['Group1'][x]=count
C:\Users\Dell\AppData\Local\Temp\ipykernel_11584\3210057935.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  coord_clean['Group1'][x]=count

In [139]:
coord_clean['Group_F']=coord_clean['Group'].astype(str)+coord_clean['Group1'].astype(str)

In [140]:
coord_clean.columns

Index(['LATITUDE', 'LONGITUDE', 'LATITUDE_diff', 'Group', 'LONGITUDE_diff',
       'Group1', 'Group_F'],
      dtype='object')

In [155]:
coord_clean1 = coord_clean.groupby('Group_F') \
       .agg({'Group_F':'size', 'LATITUDE':'mean','LONGITUDE':'mean'}) \
       .rename(columns={'Group_F':'count'}) \
       .reset_index()

coord_clean2 = coord_clean.groupby('Group_F') \
       .agg({ 'LATITUDE':'max','LONGITUDE':'max'}) \
       .rename(columns={'LATITUDE':'LATITUDE_max','LONGITUDE':'LONGITUDE_max'}) \
       .reset_index()

coord_clean3 = coord_clean.groupby('Group_F') \
       .agg({ 'LATITUDE':'min','LONGITUDE':'min'}) \
       .rename(columns={'LATITUDE':'LATITUDE_min','LONGITUDE':'LONGITUDE_min'}) \
       .reset_index()

In [156]:
coord_clean1

  Group_F  count   LATITUDE  LONGITUDE
0      00      1  17.824506  73.575439
1      10      1  18.506951  73.751221
2      11      5  18.493394  73.860809
3      21      3  18.138433  73.491669
4      22      1  18.234569  73.634491
5      23      2  18.487441  73.808883
6      24      2  18.385125  73.985367
7      34      1  18.672267  74.113769

In [157]:
coord_clean2

  Group_F  LATITUDE_max  LONGITUDE_max
0      00     17.824506      73.575439
1      10     18.506951      73.751221
2      11     18.591578      73.909149
3      21     18.203262      73.557587
4      22     18.234569      73.634491
5      23     18.555197      73.844572
6      24     18.484819      73.986053
7      34     18.672267      74.113769

In [158]:
merged_Frame = pd.merge(coord_clean1,coord_clean2,  on = 'Group_F', how='inner')
merged_Frame = pd.merge(merged_Frame,coord_clean3,  on = 'Group_F', how='inner')

In [177]:
merged_Frame

,Group_F,count,LATITUDE,LONGITUDE,LATITUDE_max,LONGITUDE_max,LATITUDE_min,LONGITUDE_min,Lat_diff,Lon_diff,Dist
0,00,1,17.824506,73.575439,17.824506,73.575439,17.824506,73.575439,0.000000,0.000000,0.000000
1,10,1,18.506951,73.751221,18.506951,73.751221,18.506951,73.751221,0.000000,0.000000,0.000000
2,11,5,18.493394,73.860809,18.591578,73.909149,18.393619,73.813019,0.098184,0.048340,2356.427111
3,21,3,18.138433,73.491669,18.203262,73.557587,18.008774,73.458710,0.064829,0.065918,1582.031143
4,22,1,18.234569,73.634491,18.234569,73.634491,18.234569,73.634491,0.000000,0.000000,0.000000
5,23,2,18.487441,73.808883,18.555197,73.844572,18.419685,73.773193,0.067756,0.035689,1626.151556
6,24,2,18.385125,73.985367,18.484819,73.986053,18.285430,73.984680,0.099694,0.000687,2392.665134
7,34,1,18.672267,74.113769,18.672267,74.113769,18.672267,74.113769,0.000000,0.000000,0.000000

In [178]:
merged_Frame['Lat_diff']=merged_Frame['LATITUDE_max']-merged_Frame['LATITUDE_min']
merged_Frame['Lon_diff']=merged_Frame['LONGITUDE_max']-merged_Frame['LONGITUDE_min']

In [176]:


merged_Frame['Dist']=merged_Frame[['Lat_diff', 'Lon_diff']].max(axis=1)*12000*2